version: '3.9'
services:
  bonfire-app:
    container_name: bonfire-app
    image: bonfire-app
    build:
      context: ./frontend/
    ports:
    - '7070:3000'
    networks:
    - network
    environment:
    - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT}
    - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    - NEXTAUTH_URL=${NEXTAUTH_URL}
    - BONFIRE_ID=${BONFIRE_ID}
    - BONFIRE_CLIENT_SECRET=${BONFIRE_CLIENT_SECRET}
    - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
    restart: unless-stopped

  bonfire-worker:
    container_name: bonfire-worker
    image: bonfire-worker
    build:
      context: ./backend/
    restart: always
    ports:
    - '3332:5000'
    networks:
    - network
    volumes:
      - ./bonfire-backend/Logs:/app/Logs

networks:
  network:
    driver: bridge
